- name: variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: print cousre information
    ansible builtin.debug:
      msg: "hello learn {{ COURSE }}, {{ DURATION }}, {{ TRAINER }}"