- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    DURATION: 120 # This is number
    COURSE: "DevSecOps with AWs"  # This is string
    IS_LIVE: true # boolean
    TOOLS: # List id starts with "-" referred as [] brackets
    - shell
    - Linux
    - Ansible
    CONCEPTS: # map/dictonary or object referred as {} flower braces
     CI: Jenkins
     SCRIPTING: "Ansible,shell,terraform,python"
  tasks:
   - name: print the course information
     ansible.builtin.debug:
       msg: "hello {{ DURATION }}, Course is: {{ COURSE }}, is_live is: {{ IS_LIVE }}, tools are: {{ TOOLS }}, Concepts are: {{ CONCEPTS }}"