- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "{{ item }}" # item here is reserved keyword
    loop:
    - krishna
    - ravi
    - rajesh
    - siva