- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,suresh,rahim,suresh"
  tasks:
  - name: check undefined variables
    ansible.builtin.debug:
      msg: "Hello {{person | default('Ramesh')}}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{persons | split(',')}}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10HR
        trainer: siva
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"